import = [
    "~/.config/alacritty/themes/themes/catppucin-macchiato.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

opacity = 0.95
blur = false

option_as_alt = "Both"

# Window dimensions (changes require restart)
dimensions = { columns = 160, lines = 30 }

# Startup mode (Fullscreen, Maximized, Windowed)
startup_mode = "Maximized"

# Automatically save window dimensions on exit
dynamic_title = true

[font]
normal.family = "MesloLGS Nerd Font Mono"

size = 18

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
]
